
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestSlave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 OperationState_Undefined1 = 0x0;		/* Mapped at index 0x2000, subindex 0x01 */
UNS8 OperationState_Undefined2 = 0x0;		/* Mapped at index 0x2000, subindex 0x02 */
UNS8 OperationState_IO_OperationState = 0x0;		/* Mapped at index 0x2000, subindex 0x03 */
UNS8 BMS_FirmwareVersion_Major = 0x0;		/* Mapped at index 0x2A00, subindex 0x01 */
UNS8 BMS_FirmwareVersion_Minor = 0x0;		/* Mapped at index 0x2A00, subindex 0x02 */
UNS8 BMS_FirmwareVersion_Build = 0x0;		/* Mapped at index 0x2A00, subindex 0x03 */
UNS32 BMS_Information_BMS_Status = 0x0;		/* Mapped at index 0x2A10, subindex 0x01 */
UNS32 BMS_Information_BMS_Warnings = 0x0;		/* Mapped at index 0x2A10, subindex 0x02 */
UNS32 BMS_Information_BMS_Errors = 0x0;		/* Mapped at index 0x2A10, subindex 0x03 */
UNS16 BMS_States_BMS_StateOfCharge = 0x0;		/* Mapped at index 0x2A11, subindex 0x01 */
UNS16 BMS_States_BMS_StateOfHealth = 0x0;		/* Mapped at index 0x2A11, subindex 0x02 */
UNS32 BMS_ActualVoltage = 0x0;		/* Mapped at index 0x2A12, subindex 0x00 */
INTEGER32 BMS_ActualCurrent = 0x0;		/* Mapped at index 0x2A13, subindex 0x00 */
INTEGER16 BMS_ActualTemp_BMS_ActualTemp1 = 0x0;		/* Mapped at index 0x2A14, subindex 0x01 */
INTEGER16 BMS_ActualTemp_BMS_ActualTemp2 = 0x0;		/* Mapped at index 0x2A14, subindex 0x02 */
INTEGER16 BMS_ActualTemp_BMS_ActualTemp3 = 0x0;		/* Mapped at index 0x2A14, subindex 0x03 */
INTEGER16 BMS_ActualTemp_BMS_ActualTemp4 = 0x0;		/* Mapped at index 0x2A14, subindex 0x04 */
UNS8 BMS_BatteryMode = 0x1;		/* Mapped at index 0x2A15, subindex 0x00 */
UNS32 BMS_ReceivedActualVoltages_BMS1_ActualVoltage = 0x0;		/* Mapped at index 0x2A16, subindex 0x01 */
UNS32 BMS_ReceivedActualVoltages_BMS2_ActualVoltage = 0x0;		/* Mapped at index 0x2A16, subindex 0x02 */
UNS32 BMS_ReceivedActualVoltages_BMS3_ActualVoltage = 0x0;		/* Mapped at index 0x2A16, subindex 0x03 */
UNS32 BMS_CellVoltages_BMS_CellVoltage1 = 0x0;		/* Mapped at index 0x2A17, subindex 0x01 */
UNS32 BMS_CellVoltages_BMS_CellVoltage2 = 0x0;		/* Mapped at index 0x2A17, subindex 0x02 */
UNS32 BMS_CellVoltages_BMS_CellVoltage3 = 0x0;		/* Mapped at index 0x2A17, subindex 0x03 */
UNS32 BMS_CellVoltages_BMS_CellVoltage4 = 0x0;		/* Mapped at index 0x2A17, subindex 0x04 */
UNS32 BMS_CellVoltages_BMS_CellVoltage5 = 0x0;		/* Mapped at index 0x2A17, subindex 0x05 */
UNS32 BMS_CellVoltages_BMS_CellVoltage6 = 0x0;		/* Mapped at index 0x2A17, subindex 0x06 */
UNS32 BMS_CellVoltages_BMS_CellVoltage7 = 0x0;		/* Mapped at index 0x2A17, subindex 0x07 */
UNS32 BMS_CellVoltages_BMS_CellVoltage8 = 0x0;		/* Mapped at index 0x2A17, subindex 0x08 */
UNS32 BMS_CellVoltages_BMS_CellVoltage9 = 0x0;		/* Mapped at index 0x2A17, subindex 0x09 */
UNS32 BMS_CellVoltages_BMS_CellVoltage10 = 0x0;		/* Mapped at index 0x2A17, subindex 0x0A */
UNS32 BMS_CellVoltages_BMS_CellVoltage11 = 0x0;		/* Mapped at index 0x2A17, subindex 0x0B */
UNS32 BMS_CellVoltages_BMS_CellVoltage12 = 0x0;		/* Mapped at index 0x2A17, subindex 0x0C */
UNS32 BMS_CellVoltages_BMS_CellVoltage13 = 0x0;		/* Mapped at index 0x2A17, subindex 0x0D */
UNS32 BMS_CellVoltages_BMS_CellVoltage14 = 0x0;		/* Mapped at index 0x2A17, subindex 0x0E */
UNS32 BMS_CellVoltages_BMS_CellVoltage15 = 0x0;		/* Mapped at index 0x2A17, subindex 0x0F */
UNS32 BMS_CellVoltages_BMS_CellVoltage16 = 0x0;		/* Mapped at index 0x2A17, subindex 0x10 */
UNS32 RTCBatteryTime = 0x0;		/* Mapped at index 0x2A18, subindex 0x00 */
UNS16 BMS_TimeInformation_BMS_RemCTime = 0x0;		/* Mapped at index 0x2A19, subindex 0x01 */
UNS16 BMS_TimeInformation_BMS_RemDTime = 0x0;		/* Mapped at index 0x2A19, subindex 0x02 */
UNS16 BMS_CycleCount = 0x0;		/* Mapped at index 0x2A1A, subindex 0x00 */
UNS16 BMS_ChargeCycleVoltages_BMS_VolAtStartChargeCycle = 0x0;		/* Mapped at index 0x2A1B, subindex 0x01 */
UNS16 BMS_ChargeCycleVoltages_BMS_VolAtEndChargeCycle = 0x0;		/* Mapped at index 0x2A1B, subindex 0x02 */
INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature1AtStartChargeCycle = 0x0;		/* Mapped at index 0x2A1C, subindex 0x01 */
INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature1AtEndChargeCycle = 0x0;		/* Mapped at index 0x2A1C, subindex 0x02 */
INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature2AtStartChargeCycle = 0x0;		/* Mapped at index 0x2A1C, subindex 0x03 */
INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature2AtEndChargeCycle = 0x0;		/* Mapped at index 0x2A1C, subindex 0x04 */
INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature3AtStartChargeCycle = 0x0;		/* Mapped at index 0x2A1C, subindex 0x05 */
INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature3AtEndChargeCycle = 0x0;		/* Mapped at index 0x2A1C, subindex 0x06 */
INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature4AtStartChargeCycle = 0x0;		/* Mapped at index 0x2A1C, subindex 0x07 */
INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature4AtEndChargeCycle = 0x0;		/* Mapped at index 0x2A1C, subindex 0x08 */
UNS16 BMS_ChargeCycleSOC_BMS_SOCAtStartChargeCycle = 0x0;		/* Mapped at index 0x2A1D, subindex 0x01 */
UNS16 BMS_ChargeCycleSOC_BMS_SOCAtEndChargeCycle = 0x0;		/* Mapped at index 0x2A1D, subindex 0x02 */
UNS32 BMS_ChargeCycleTimeStamp_BMS_TimeStampAtStartChargeCycle = 0x0;		/* Mapped at index 0x2A1E, subindex 0x01 */
UNS32 BMS_ChargeCycleTimeStamp_BMS_TimeStampAtEndChargeCycle = 0x0;		/* Mapped at index 0x2A1E, subindex 0x02 */
INTEGER8 TemperatureWarning_BMS_HighTemperWarningLevel = 0x3C;		/* Mapped at index 0x2A1F, subindex 0x01 */
INTEGER8 TemperatureWarning_BMS_LowTemperWarningLevel = 0xEB;		/* Mapped at index 0x2A1F, subindex 0x02 */
UNS16 HighVolWarningLevel_BMS_HighVoltageWarningLevel = 0x28A;		/* Mapped at index 0x2A20, subindex 0x01 */
UNS16 HighVolWarningLevel_BMS_LowVoltageWarningLevel = 0x190;		/* Mapped at index 0x2A20, subindex 0x02 */
UNS16 BMS_StartCapacity = 0x220;		/* Mapped at index 0x2A21, subindex 0x00 */
INTEGER16 BMS_TemperatureExtremes_BMS_HighestTemperature1 = 0x0;		/* Mapped at index 0x2A22, subindex 0x01 */
INTEGER16 BMS_TemperatureExtremes_BMS_LowestTemperature1 = 0x0;		/* Mapped at index 0x2A22, subindex 0x02 */
INTEGER16 BMS_TemperatureExtremes_BMS_HighestTemperature2 = 0x0;		/* Mapped at index 0x2A22, subindex 0x03 */
INTEGER16 BMS_TemperatureExtremes_BMS_LowestTemperature2 = 0x0;		/* Mapped at index 0x2A22, subindex 0x04 */
INTEGER16 BMS_TemperatureExtremes_BMS_HighestTemperature3 = 0x0;		/* Mapped at index 0x2A22, subindex 0x05 */
INTEGER16 BMS_TemperatureExtremes_BMS_LowestTemperature3 = 0x0;		/* Mapped at index 0x2A22, subindex 0x06 */
INTEGER16 BMS_TemperatureExtremes_BMS_HighestTemperature4 = 0x0;		/* Mapped at index 0x2A22, subindex 0x07 */
INTEGER16 BMS_TemperatureExtremes_BMS_LowestTemperature4 = 0x0;		/* Mapped at index 0x2A22, subindex 0x08 */
UNS16 BMS_VoltageExtremes_BMS_HighestVoltage = 0x0;		/* Mapped at index 0x2A23, subindex 0x01 */
UNS16 BMS_VoltageExtremes_BMS_LowestVoltage = 0x0;		/* Mapped at index 0x2A23, subindex 0x02 */
UNS16 BMS_CurrentExtremes_BMS_HighestChargeCurrent = 0x0;		/* Mapped at index 0x2A24, subindex 0x01 */
UNS16 BMS_CurrentExtremes_BMS_HighestDischargeCurrent = 0x0;		/* Mapped at index 0x2A24, subindex 0x02 */
UNS8 BMS_DOD_BMS_MaximumDOD = 0x0;		/* Mapped at index 0x2A25, subindex 0x01 */
UNS8 BMS_DOD_BMS_AvarageDOD = 0x0;		/* Mapped at index 0x2A25, subindex 0x02 */
UNS16 BMS_IntervalLogPointer = 0x0;		/* Mapped at index 0x2A26, subindex 0x00 */
UNS16 BMS_IntervalLogRequest = 0x0;		/* Mapped at index 0x2A27, subindex 0x00 */
UNS8 BMS_IntervalLogResponse = 0x0;		/* Mapped at index 0x2A28, subindex 0x00 */
INTEGER8 BMS_IntervalLogData[] = {0x32,0x31,0x30,0x29,0x28,0x27,0x26,0x25,0x24,0x23,0x22,0x21,0x20,0x19,0x2f,0x2e,
		0x2c,0x2d,0x2b,0x29,0x28,0x27,0x26,0x25,0x32,0x31,0x30,0x29,0x28,0x27,0x26,0x25,0,1,2,3,4,5,6,7,8,9};		/* Mapped at index 0x2A29, subindex 0x00 */
UNS8 BMS_IntervalLogClear = 0x0;		/* Mapped at index 0x2A2A, subindex 0x00 */
INTEGER8 BMS_CycleLogData[] = "\x32";		/* Mapped at index 0x2A2B, subindex 0x00 */
UNS8 BMS_CycleLogClear = 0x0;		/* Mapped at index 0x2A2C, subindex 0x00 */
INTEGER8 BMS_ErrorLogData[] = "\x32";		/* Mapped at index 0x2A2D, subindex 0x00 */
UNS8 BMS_ErrorLogClear = 0x0;		/* Mapped at index 0x2A2E, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestSlave_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestSlave_iam_a_slave = 1;

TIMER_HANDLE TestSlave_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestSlave_obj1000 = 0x0;	/* 0 */
                    subindex TestSlave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestSlave_obj1001 = 0x0;	/* 0 */
                    subindex TestSlave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestSlave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t TestSlave_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TestSlave_obj1005 = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 TestSlave_obj1006 = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1006 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    INTEGER8 TestSlave_obj1008[10] = "";
                    subindex TestSlave_Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&TestSlave_obj1008 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 TestSlave_obj1014 = 0x80;	/* 128 */
                    subindex TestSlave_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 TestSlave_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1016[] = 
                    {
                      0x305DC	/* 198108 */
                    };
                    subindex TestSlave_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestSlave_obj1017 = 10000;	/* 1000 */
					//UNS16 TestSlave_obj1017 = 0xF1;  // set heart cycle author: craigtao
                    ODCallback_t TestSlave_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestSlave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1018_Serial_Number = 0x00;	/* 0 */
                    subindex TestSlave_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 TestSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex TestSlave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1400_COB_ID_used_by_PDO = 0x2A3;	/* 675 */
                    UNS8 TestSlave_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1400_Event_Timer = 0x0;	/* 0 */
                    subindex TestSlave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1400_Event_Timer }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1401 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1401_COB_ID_used_by_PDO = 0x1DA;	/* 1073742298 */
                    UNS8 TestSlave_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1401_Event_Timer = 0x0;	/* 0 */
                    subindex TestSlave_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1401_Event_Timer }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1402 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1402_COB_ID_used_by_PDO = 0x1DB;	/* 1073742299 */
                    UNS8 TestSlave_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1402_Event_Timer = 0x0;	/* 0 */
                    subindex TestSlave_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1402_Event_Timer }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1403 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1403_COB_ID_used_by_PDO = 0x1DC;	/* 1073742300 */
                    UNS8 TestSlave_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1403_Event_Timer = 0x0;	/* 0 */
                    subindex TestSlave_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1403_Event_Timer }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1404 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1404_COB_ID_used_by_PDO = 0x183;	/* 1073742211 */
                    UNS8 TestSlave_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1404_Event_Timer = 0x0;	/* 0 */
                    subindex TestSlave_Index1404[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1404 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1404_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1404_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1404_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1404_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1404_Event_Timer }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1600[] = 
                    {
                      0x2A180020	/* 706215968 */
                    };
                    subindex TestSlave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1600[0] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1601[] = 
                    {
                      0x2A160120	/* 706085152 */
                    };
                    subindex TestSlave_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1601[0] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1602[] = 
                    {
                      0x2A160220	/* 706085408 */
                    };
                    subindex TestSlave_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[0] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1603 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1603[] = 
                    {
                      0x2A160320	/* 706085664 */
                    };
                    subindex TestSlave_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[0] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1604 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1604[] = 
                    {
                      0x20000308	/* 536871688 */
                    };
                    subindex TestSlave_Index1604[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1604 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1604[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 TestSlave_obj1800_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestSlave_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1800_Event_Timer }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1801 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1801_COB_ID_used_by_PDO = 0x190;	/* 400 */
                    UNS8 TestSlave_obj1801_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestSlave_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1801_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1801_Event_Timer }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1802 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1802_COB_ID_used_by_PDO = 0x1A0;	/* 416 */
                    UNS8 TestSlave_obj1802_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestSlave_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1802_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1802_Event_Timer }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1803 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1803_COB_ID_used_by_PDO = 0x1B0;	/* 432 */
                    UNS8 TestSlave_obj1803_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestSlave_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1803_Event_Timer = 0x00;	/* 20000 */
                    ODCallback_t TestSlave_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1803_Event_Timer }
                     };

/* index 0x1804 :   Transmit PDO 5 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1804 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1804_COB_ID_used_by_PDO = 0x1C0;	/* 448 */
                    UNS8 TestSlave_obj1804_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestSlave_obj1804_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1804_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1804_Event_Timer = 0x00;	/* 100 */
                    ODCallback_t TestSlave_Index1804_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1804[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1804 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1804_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1804_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1804_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1804_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1804_Event_Timer }
                     };

/* index 0x1805 :   Transmit PDO 6 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1805 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1805_COB_ID_used_by_PDO = 0x1D0;	/* 464 */
                    UNS8 TestSlave_obj1805_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestSlave_obj1805_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1805_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1805_Event_Timer = 0x00;	/* 1000 */
                    ODCallback_t TestSlave_Index1805_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1805[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1805 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1805_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1805_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1805_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1805_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1805_Event_Timer }
                     };

/* index 0x1806 :   Transmit PDO 7 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1806 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1806_COB_ID_used_by_PDO = 0x1E0;	/* 480 */
                    UNS8 TestSlave_obj1806_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestSlave_obj1806_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1806_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1806_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1806_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1806[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1806 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1806_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1806_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1806_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1806_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1806_Event_Timer }
                     };

/* index 0x1807 :   Transmit PDO 8 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1807 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1807_COB_ID_used_by_PDO = 0x1F0;	/* 496 */
                    UNS8 TestSlave_obj1807_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestSlave_obj1807_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1807_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1807_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1807_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1807[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1807 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1807_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1807_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1807_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1807_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1807_Event_Timer }
                     };

/* index 0x1808 :   Transmit PDO 9 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1808 = 5; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1808_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 TestSlave_obj1808_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 TestSlave_obj1808_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1808_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1808_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1808_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1808[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1808 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1808_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1808_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1808_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1808_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1808_Event_Timer }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A00[] = 
                    {
                      0x2A100120	/* 705691936 */
                    };
                    subindex TestSlave_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A00[0] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A01 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A01[] = 
                    {
                      0x2A100220	/* 705692192 */
                    };
                    subindex TestSlave_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A01[0] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A02 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A02[] = 
                    {
                      0x2A100320	/* 705692448 */
                    };
                    subindex TestSlave_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A02[0] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A03 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A03[] = 
                    {
                      0x2A110110	/* 705757456 */
                    };
                    subindex TestSlave_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A03[0] }
                     };

/* index 0x1A04 :   Transmit PDO 5 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A04 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A04[] = 
                    {
                      0x2A130020	/* 705888288 */
                    };
                    subindex TestSlave_Index1A04[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A04 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A04[0] }
                     };

/* index 0x1A05 :   Transmit PDO 6 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A05 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A05[] = 
                    {
                      0x2A120020	/* 705822752 */
                    };
                    subindex TestSlave_Index1A05[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A05 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A05[0] }
                     };

/* index 0x1A06 :   Transmit PDO 7 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A06 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A06[] = 
                    {
                      0x2A190110	/* 706281744 */
                    };
                    subindex TestSlave_Index1A06[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A06 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A06[0] }
                     };

/* index 0x1A07 :   Transmit PDO 8 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A07 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A07[] = 
                    {
                      0x2A190210	/* 706282000 */
                    };
                    subindex TestSlave_Index1A07[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A07 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A07[0] }
                     };

/* index 0x1A08 :   Transmit PDO 9 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A08 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A08[] = 
                    {
                      0x2A280001	/* 707264513 */
                    };
                    subindex TestSlave_Index1A08[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A08 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A08[0] }
                     };

/* index 0x1F80 :   NMTStartup. */
                    UNS32 TestSlave_obj1F80 = 0x0;	/* 0 */
                    subindex TestSlave_Index1F80[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1F80 }
                     };

/* index 0x2000 :   Mapped variable OperationState */
                    UNS8 TestSlave_highestSubIndex_obj2000 = 3; /* number of subindex - 1*/
                    subindex TestSlave_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2000 },
                       { RW, uint8, sizeof (UNS8), (void*)&OperationState_Undefined1 },
                       { RW, uint8, sizeof (UNS8), (void*)&OperationState_Undefined2 },
                       { RW, uint8, sizeof (UNS8), (void*)&OperationState_IO_OperationState }
                     };

/* index 0x2A00 :   Mapped variable BMS_FirmwareVersion */
                    UNS8 TestSlave_highestSubIndex_obj2A00 = 3; /* number of subindex - 1*/
                    subindex TestSlave_Index2A00[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A00 },
                       { RW, uint8, sizeof (UNS8), (void*)&BMS_FirmwareVersion_Major },
                       { RW, uint8, sizeof (UNS8), (void*)&BMS_FirmwareVersion_Minor },
                       { RW, uint8, sizeof (UNS8), (void*)&BMS_FirmwareVersion_Build }
                     };

/* index 0x2A10 :   Mapped variable BMS_Information */
                    UNS8 TestSlave_highestSubIndex_obj2A10 = 3; /* number of subindex - 1*/
                    subindex TestSlave_Index2A10[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A10 },
                       { RW, uint32, sizeof (UNS32), (void*)&BMS_Information_BMS_Status },
                       { RW, uint32, sizeof (UNS32), (void*)&BMS_Information_BMS_Warnings },
                       { RW, uint32, sizeof (UNS32), (void*)&BMS_Information_BMS_Errors }
                     };

/* index 0x2A11 :   Mapped variable BMS_States */
                    UNS8 TestSlave_highestSubIndex_obj2A11 = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A11[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A11 },
                       { RW, uint16, sizeof (UNS16), (void*)&BMS_States_BMS_StateOfCharge },
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_States_BMS_StateOfHealth }
                     };

/* index 0x2A12 :   Mapped variable BMS_ActualVoltage */
                    subindex TestSlave_Index2A12[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&BMS_ActualVoltage }
                     };

/* index 0x2A13 :   Mapped variable BMS_ActualCurrent */
                    subindex TestSlave_Index2A13[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&BMS_ActualCurrent }
                     };

/* index 0x2A14 :   Mapped variable BMS_ActualTemp */
                    UNS8 TestSlave_highestSubIndex_obj2A14 = 4; /* number of subindex - 1*/
                    subindex TestSlave_Index2A14[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A14 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ActualTemp_BMS_ActualTemp1 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ActualTemp_BMS_ActualTemp2 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ActualTemp_BMS_ActualTemp3 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ActualTemp_BMS_ActualTemp4 }
                     };

/* index 0x2A15 :   Mapped variable BMS_BatteryMode */
                    subindex TestSlave_Index2A15[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&BMS_BatteryMode }
                     };

/* index 0x2A16 :   Mapped variable BMS_ReceivedActualVoltages */
                    UNS8 TestSlave_highestSubIndex_obj2A16 = 3; /* number of subindex - 1*/
                    subindex TestSlave_Index2A16[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A16 },
                       { RW, uint32, sizeof (UNS32), (void*)&BMS_ReceivedActualVoltages_BMS1_ActualVoltage },
                       { RW, uint32, sizeof (UNS32), (void*)&BMS_ReceivedActualVoltages_BMS2_ActualVoltage },
                       { RW, uint32, sizeof (UNS32), (void*)&BMS_ReceivedActualVoltages_BMS3_ActualVoltage }
                     };

/* index 0x2A17 :   Mapped variable BMS_CellVoltages */
                    UNS8 TestSlave_highestSubIndex_obj2A17 = 16; /* number of subindex - 1*/
                    subindex TestSlave_Index2A17[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A17 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage1 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage2 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage3 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage4 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage5 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage6 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage7 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage8 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage9 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage10 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage11 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage12 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage13 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage14 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage15 },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_CellVoltages_BMS_CellVoltage16 }
                     };

/* index 0x2A18 :   Mapped variable RTCBatteryTime */
                    subindex TestSlave_Index2A18[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&RTCBatteryTime }
                     };

/* index 0x2A19 :   Mapped variable BMS_TimeInformation */
                    UNS8 TestSlave_highestSubIndex_obj2A19 = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A19[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A19 },
                       { RW, uint16, sizeof (UNS16), (void*)&BMS_TimeInformation_BMS_RemCTime },
                       { RW, uint16, sizeof (UNS16), (void*)&BMS_TimeInformation_BMS_RemDTime }
                     };

/* index 0x2A1A :   Mapped variable BMS_CycleCount */
                    subindex TestSlave_Index2A1A[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_CycleCount }
                     };

/* index 0x2A1B :   Mapped variable BMS_ChargeCycleVoltages */
                    UNS8 TestSlave_highestSubIndex_obj2A1B = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A1B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A1B },
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_ChargeCycleVoltages_BMS_VolAtStartChargeCycle },
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_ChargeCycleVoltages_BMS_VolAtEndChargeCycle }
                     };

/* index 0x2A1C :   Mapped variable BMS_ChargeCycleTemperatures */
                    UNS8 TestSlave_highestSubIndex_obj2A1C = 8; /* number of subindex - 1*/
                    subindex TestSlave_Index2A1C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A1C },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ChargeCycleTemperatures_BMS_Temperature1AtStartChargeCycle },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ChargeCycleTemperatures_BMS_Temperature1AtEndChargeCycle },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ChargeCycleTemperatures_BMS_Temperature2AtStartChargeCycle },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ChargeCycleTemperatures_BMS_Temperature2AtEndChargeCycle },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ChargeCycleTemperatures_BMS_Temperature3AtStartChargeCycle },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ChargeCycleTemperatures_BMS_Temperature3AtEndChargeCycle },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ChargeCycleTemperatures_BMS_Temperature4AtStartChargeCycle },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_ChargeCycleTemperatures_BMS_Temperature4AtEndChargeCycle }
                     };

/* index 0x2A1D :   Mapped variable BMS_ChargeCycleSOC */
                    UNS8 TestSlave_highestSubIndex_obj2A1D = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A1D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A1D },
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_ChargeCycleSOC_BMS_SOCAtStartChargeCycle },
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_ChargeCycleSOC_BMS_SOCAtEndChargeCycle }
                     };

/* index 0x2A1E :   Mapped variable BMS_ChargeCycleTimeStamp */
                    UNS8 TestSlave_highestSubIndex_obj2A1E = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A1E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A1E },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_ChargeCycleTimeStamp_BMS_TimeStampAtStartChargeCycle },
                       { RO, uint32, sizeof (UNS32), (void*)&BMS_ChargeCycleTimeStamp_BMS_TimeStampAtEndChargeCycle }
                     };

/* index 0x2A1F :   Mapped variable TemperatureWarning */
                    UNS8 TestSlave_highestSubIndex_obj2A1F = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A1F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A1F },
                       { RW, int8, sizeof (INTEGER8), (void*)&TemperatureWarning_BMS_HighTemperWarningLevel },
                       { RW, int8, sizeof (INTEGER8), (void*)&TemperatureWarning_BMS_LowTemperWarningLevel }
                     };

/* index 0x2A20 :   Mapped variable HighVolWarningLevel */
                    UNS8 TestSlave_highestSubIndex_obj2A20 = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A20[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A20 },
                       { RW, uint16, sizeof (UNS16), (void*)&HighVolWarningLevel_BMS_HighVoltageWarningLevel },
                       { RW, uint16, sizeof (UNS16), (void*)&HighVolWarningLevel_BMS_LowVoltageWarningLevel }
                     };

/* index 0x2A21 :   Mapped variable BMS_StartCapacity */
                    subindex TestSlave_Index2A21[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_StartCapacity }
                     };

/* index 0x2A22 :   Mapped variable BMS_TemperatureExtremes */
                    UNS8 TestSlave_highestSubIndex_obj2A22 = 8; /* number of subindex - 1*/
                    subindex TestSlave_Index2A22[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A22 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_TemperatureExtremes_BMS_HighestTemperature1 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_TemperatureExtremes_BMS_LowestTemperature1 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_TemperatureExtremes_BMS_HighestTemperature2 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_TemperatureExtremes_BMS_LowestTemperature2 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_TemperatureExtremes_BMS_HighestTemperature3 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_TemperatureExtremes_BMS_LowestTemperature3 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_TemperatureExtremes_BMS_HighestTemperature4 },
                       { RO, int16, sizeof (INTEGER16), (void*)&BMS_TemperatureExtremes_BMS_LowestTemperature4 }
                     };

/* index 0x2A23 :   Mapped variable BMS_VoltageExtremes */
                    UNS8 TestSlave_highestSubIndex_obj2A23 = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A23[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A23 },
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_VoltageExtremes_BMS_HighestVoltage },
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_VoltageExtremes_BMS_LowestVoltage }
                     };

/* index 0x2A24 :   Mapped variable BMS_CurrentExtremes */
                    UNS8 TestSlave_highestSubIndex_obj2A24 = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A24[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A24 },
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_CurrentExtremes_BMS_HighestChargeCurrent },
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_CurrentExtremes_BMS_HighestDischargeCurrent }
                     };

/* index 0x2A25 :   Mapped variable BMS_DOD */
                    UNS8 TestSlave_highestSubIndex_obj2A25 = 2; /* number of subindex - 1*/
                    subindex TestSlave_Index2A25[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj2A25 },
                       { RO, uint8, sizeof (UNS8), (void*)&BMS_DOD_BMS_MaximumDOD },
                       { RO, uint8, sizeof (UNS8), (void*)&BMS_DOD_BMS_AvarageDOD }
                     };

/* index 0x2A26 :   Mapped variable BMS_IntervalLogPointer */
                    subindex TestSlave_Index2A26[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_IntervalLogPointer }
                     };

/* index 0x2A27 :   Mapped variable BMS_IntervalLogRequest */
                    subindex TestSlave_Index2A27[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&BMS_IntervalLogRequest }
                     };

/* index 0x2A28 :   Mapped variable BMS_IntervalLogResponse */
                    subindex TestSlave_Index2A28[] = 
                     {
                       { RW, boolean, sizeof (UNS8), (void*)&BMS_IntervalLogResponse }
                     };

/* index 0x2A29 :   Mapped variable BMS_IntervalLogData */
                    subindex TestSlave_Index2A29[] = 
                     {
                       { RO, domain, 127, (void*)&BMS_IntervalLogData }
                     };


/* index 0x2A2A :   Mapped variable BMS_IntervalLogClear */
                    subindex TestSlave_Index2A2A[] = 
                     {
                       { WO, boolean, sizeof (UNS8), (void*)&BMS_IntervalLogClear }
                     };

/* index 0x2A2B :   Mapped variable BMS_CycleLogData */
                    subindex TestSlave_Index2A2B[] = 
                     {
                       { RO, domain, 1, (void*)&BMS_CycleLogData }
                     };

/* index 0x2A2C :   Mapped variable BMS_CycleLogClear */
                    subindex TestSlave_Index2A2C[] = 
                     {
                       { WO, boolean, sizeof (UNS8), (void*)&BMS_CycleLogClear }
                     };

/* index 0x2A2D :   Mapped variable BMS_ErrorLogData */
                    subindex TestSlave_Index2A2D[] = 
                     {
                       { RO, domain, 1, (void*)&BMS_ErrorLogData }
                     };

/* index 0x2A2E :   Mapped variable BMS_ErrorLogClear */
                    subindex TestSlave_Index2A2E[] = 
                     {
                       { WO, boolean, sizeof (UNS8), (void*)&BMS_ErrorLogClear }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestSlave_objdict[] = 
{
  { (subindex*)TestSlave_Index1000,sizeof(TestSlave_Index1000)/sizeof(TestSlave_Index1000[0]), 0x1000},
  { (subindex*)TestSlave_Index1001,sizeof(TestSlave_Index1001)/sizeof(TestSlave_Index1001[0]), 0x1001},
  { (subindex*)TestSlave_Index1005,sizeof(TestSlave_Index1005)/sizeof(TestSlave_Index1005[0]), 0x1005},
  { (subindex*)TestSlave_Index1006,sizeof(TestSlave_Index1006)/sizeof(TestSlave_Index1006[0]), 0x1006},
  { (subindex*)TestSlave_Index1008,sizeof(TestSlave_Index1008)/sizeof(TestSlave_Index1008[0]), 0x1008},
  { (subindex*)TestSlave_Index1014,sizeof(TestSlave_Index1014)/sizeof(TestSlave_Index1014[0]), 0x1014},
  { (subindex*)TestSlave_Index1016,sizeof(TestSlave_Index1016)/sizeof(TestSlave_Index1016[0]), 0x1016},
  { (subindex*)TestSlave_Index1017,sizeof(TestSlave_Index1017)/sizeof(TestSlave_Index1017[0]), 0x1017},
  { (subindex*)TestSlave_Index1018,sizeof(TestSlave_Index1018)/sizeof(TestSlave_Index1018[0]), 0x1018},
  { (subindex*)TestSlave_Index1200,sizeof(TestSlave_Index1200)/sizeof(TestSlave_Index1200[0]), 0x1200},
  { (subindex*)TestSlave_Index1400,sizeof(TestSlave_Index1400)/sizeof(TestSlave_Index1400[0]), 0x1400},
  { (subindex*)TestSlave_Index1401,sizeof(TestSlave_Index1401)/sizeof(TestSlave_Index1401[0]), 0x1401},
  { (subindex*)TestSlave_Index1402,sizeof(TestSlave_Index1402)/sizeof(TestSlave_Index1402[0]), 0x1402},
  { (subindex*)TestSlave_Index1403,sizeof(TestSlave_Index1403)/sizeof(TestSlave_Index1403[0]), 0x1403},
  { (subindex*)TestSlave_Index1404,sizeof(TestSlave_Index1404)/sizeof(TestSlave_Index1404[0]), 0x1404},
  { (subindex*)TestSlave_Index1600,sizeof(TestSlave_Index1600)/sizeof(TestSlave_Index1600[0]), 0x1600},
  { (subindex*)TestSlave_Index1601,sizeof(TestSlave_Index1601)/sizeof(TestSlave_Index1601[0]), 0x1601},
  { (subindex*)TestSlave_Index1602,sizeof(TestSlave_Index1602)/sizeof(TestSlave_Index1602[0]), 0x1602},
  { (subindex*)TestSlave_Index1603,sizeof(TestSlave_Index1603)/sizeof(TestSlave_Index1603[0]), 0x1603},
  { (subindex*)TestSlave_Index1604,sizeof(TestSlave_Index1604)/sizeof(TestSlave_Index1604[0]), 0x1604},
  { (subindex*)TestSlave_Index1800,sizeof(TestSlave_Index1800)/sizeof(TestSlave_Index1800[0]), 0x1800},
  { (subindex*)TestSlave_Index1801,sizeof(TestSlave_Index1801)/sizeof(TestSlave_Index1801[0]), 0x1801},
  { (subindex*)TestSlave_Index1802,sizeof(TestSlave_Index1802)/sizeof(TestSlave_Index1802[0]), 0x1802},
  { (subindex*)TestSlave_Index1803,sizeof(TestSlave_Index1803)/sizeof(TestSlave_Index1803[0]), 0x1803},
  { (subindex*)TestSlave_Index1804,sizeof(TestSlave_Index1804)/sizeof(TestSlave_Index1804[0]), 0x1804},
  { (subindex*)TestSlave_Index1805,sizeof(TestSlave_Index1805)/sizeof(TestSlave_Index1805[0]), 0x1805},
  { (subindex*)TestSlave_Index1806,sizeof(TestSlave_Index1806)/sizeof(TestSlave_Index1806[0]), 0x1806},
  { (subindex*)TestSlave_Index1807,sizeof(TestSlave_Index1807)/sizeof(TestSlave_Index1807[0]), 0x1807},
  { (subindex*)TestSlave_Index1808,sizeof(TestSlave_Index1808)/sizeof(TestSlave_Index1808[0]), 0x1808},
  { (subindex*)TestSlave_Index1A00,sizeof(TestSlave_Index1A00)/sizeof(TestSlave_Index1A00[0]), 0x1A00},
  { (subindex*)TestSlave_Index1A01,sizeof(TestSlave_Index1A01)/sizeof(TestSlave_Index1A01[0]), 0x1A01},
  { (subindex*)TestSlave_Index1A02,sizeof(TestSlave_Index1A02)/sizeof(TestSlave_Index1A02[0]), 0x1A02},
  { (subindex*)TestSlave_Index1A03,sizeof(TestSlave_Index1A03)/sizeof(TestSlave_Index1A03[0]), 0x1A03},
  { (subindex*)TestSlave_Index1A04,sizeof(TestSlave_Index1A04)/sizeof(TestSlave_Index1A04[0]), 0x1A04},
  { (subindex*)TestSlave_Index1A05,sizeof(TestSlave_Index1A05)/sizeof(TestSlave_Index1A05[0]), 0x1A05},
  { (subindex*)TestSlave_Index1A06,sizeof(TestSlave_Index1A06)/sizeof(TestSlave_Index1A06[0]), 0x1A06},
  { (subindex*)TestSlave_Index1A07,sizeof(TestSlave_Index1A07)/sizeof(TestSlave_Index1A07[0]), 0x1A07},
  { (subindex*)TestSlave_Index1A08,sizeof(TestSlave_Index1A08)/sizeof(TestSlave_Index1A08[0]), 0x1A08},
  { (subindex*)TestSlave_Index1F80,sizeof(TestSlave_Index1F80)/sizeof(TestSlave_Index1F80[0]), 0x1F80},
  { (subindex*)TestSlave_Index2000,sizeof(TestSlave_Index2000)/sizeof(TestSlave_Index2000[0]), 0x2000},
  { (subindex*)TestSlave_Index2A00,sizeof(TestSlave_Index2A00)/sizeof(TestSlave_Index2A00[0]), 0x2A00},
  { (subindex*)TestSlave_Index2A10,sizeof(TestSlave_Index2A10)/sizeof(TestSlave_Index2A10[0]), 0x2A10},
  { (subindex*)TestSlave_Index2A11,sizeof(TestSlave_Index2A11)/sizeof(TestSlave_Index2A11[0]), 0x2A11},
  { (subindex*)TestSlave_Index2A12,sizeof(TestSlave_Index2A12)/sizeof(TestSlave_Index2A12[0]), 0x2A12},
  { (subindex*)TestSlave_Index2A13,sizeof(TestSlave_Index2A13)/sizeof(TestSlave_Index2A13[0]), 0x2A13},
  { (subindex*)TestSlave_Index2A14,sizeof(TestSlave_Index2A14)/sizeof(TestSlave_Index2A14[0]), 0x2A14},
  { (subindex*)TestSlave_Index2A15,sizeof(TestSlave_Index2A15)/sizeof(TestSlave_Index2A15[0]), 0x2A15},
  { (subindex*)TestSlave_Index2A16,sizeof(TestSlave_Index2A16)/sizeof(TestSlave_Index2A16[0]), 0x2A16},
  { (subindex*)TestSlave_Index2A17,sizeof(TestSlave_Index2A17)/sizeof(TestSlave_Index2A17[0]), 0x2A17},
  { (subindex*)TestSlave_Index2A18,sizeof(TestSlave_Index2A18)/sizeof(TestSlave_Index2A18[0]), 0x2A18},
  { (subindex*)TestSlave_Index2A19,sizeof(TestSlave_Index2A19)/sizeof(TestSlave_Index2A19[0]), 0x2A19},
  { (subindex*)TestSlave_Index2A1A,sizeof(TestSlave_Index2A1A)/sizeof(TestSlave_Index2A1A[0]), 0x2A1A},
  { (subindex*)TestSlave_Index2A1B,sizeof(TestSlave_Index2A1B)/sizeof(TestSlave_Index2A1B[0]), 0x2A1B},
  { (subindex*)TestSlave_Index2A1C,sizeof(TestSlave_Index2A1C)/sizeof(TestSlave_Index2A1C[0]), 0x2A1C},
  { (subindex*)TestSlave_Index2A1D,sizeof(TestSlave_Index2A1D)/sizeof(TestSlave_Index2A1D[0]), 0x2A1D},
  { (subindex*)TestSlave_Index2A1E,sizeof(TestSlave_Index2A1E)/sizeof(TestSlave_Index2A1E[0]), 0x2A1E},
  { (subindex*)TestSlave_Index2A1F,sizeof(TestSlave_Index2A1F)/sizeof(TestSlave_Index2A1F[0]), 0x2A1F},
  { (subindex*)TestSlave_Index2A20,sizeof(TestSlave_Index2A20)/sizeof(TestSlave_Index2A20[0]), 0x2A20},
  { (subindex*)TestSlave_Index2A21,sizeof(TestSlave_Index2A21)/sizeof(TestSlave_Index2A21[0]), 0x2A21},
  { (subindex*)TestSlave_Index2A22,sizeof(TestSlave_Index2A22)/sizeof(TestSlave_Index2A22[0]), 0x2A22},
  { (subindex*)TestSlave_Index2A23,sizeof(TestSlave_Index2A23)/sizeof(TestSlave_Index2A23[0]), 0x2A23},
  { (subindex*)TestSlave_Index2A24,sizeof(TestSlave_Index2A24)/sizeof(TestSlave_Index2A24[0]), 0x2A24},
  { (subindex*)TestSlave_Index2A25,sizeof(TestSlave_Index2A25)/sizeof(TestSlave_Index2A25[0]), 0x2A25},
  { (subindex*)TestSlave_Index2A26,sizeof(TestSlave_Index2A26)/sizeof(TestSlave_Index2A26[0]), 0x2A26},
  { (subindex*)TestSlave_Index2A27,sizeof(TestSlave_Index2A27)/sizeof(TestSlave_Index2A27[0]), 0x2A27},
  { (subindex*)TestSlave_Index2A28,sizeof(TestSlave_Index2A28)/sizeof(TestSlave_Index2A28[0]), 0x2A28},
  { (subindex*)TestSlave_Index2A29,sizeof(TestSlave_Index2A29)/sizeof(TestSlave_Index2A29[0]), 0x2A29},
  { (subindex*)TestSlave_Index2A2A,sizeof(TestSlave_Index2A2A)/sizeof(TestSlave_Index2A2A[0]), 0x2A2A},
  { (subindex*)TestSlave_Index2A2B,sizeof(TestSlave_Index2A2B)/sizeof(TestSlave_Index2A2B[0]), 0x2A2B},
  { (subindex*)TestSlave_Index2A2C,sizeof(TestSlave_Index2A2C)/sizeof(TestSlave_Index2A2C[0]), 0x2A2C},
  { (subindex*)TestSlave_Index2A2D,sizeof(TestSlave_Index2A2D)/sizeof(TestSlave_Index2A2D[0]), 0x2A2D},
  { (subindex*)TestSlave_Index2A2E,sizeof(TestSlave_Index2A2E)/sizeof(TestSlave_Index2A2E[0]), 0x2A2E},
};

const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = TestSlave_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = TestSlave_Index1006_callbacks; break;
		case 0x1008: i = 4;break;
		case 0x1014: i = 5;break;
		case 0x1016: i = 6;break;
		case 0x1017: i = 7;*callbacks = TestSlave_Index1017_callbacks; break;
		case 0x1018: i = 8;break;
		case 0x1200: i = 9;break;
		case 0x1400: i = 10;break;
		case 0x1401: i = 11;break;
		case 0x1402: i = 12;break;
		case 0x1403: i = 13;break;
		case 0x1404: i = 14;break;
		case 0x1600: i = 15;break;
		case 0x1601: i = 16;break;
		case 0x1602: i = 17;break;
		case 0x1603: i = 18;break;
		case 0x1604: i = 19;break;
		case 0x1800: i = 20;*callbacks = TestSlave_Index1800_callbacks; break;
		case 0x1801: i = 21;*callbacks = TestSlave_Index1801_callbacks; break;
		case 0x1802: i = 22;*callbacks = TestSlave_Index1802_callbacks; break;
		case 0x1803: i = 23;*callbacks = TestSlave_Index1803_callbacks; break;
		case 0x1804: i = 24;*callbacks = TestSlave_Index1804_callbacks; break;
		case 0x1805: i = 25;*callbacks = TestSlave_Index1805_callbacks; break;
		case 0x1806: i = 26;*callbacks = TestSlave_Index1806_callbacks; break;
		case 0x1807: i = 27;*callbacks = TestSlave_Index1807_callbacks; break;
		case 0x1808: i = 28;*callbacks = TestSlave_Index1808_callbacks; break;
		case 0x1A00: i = 29;break;
		case 0x1A01: i = 30;break;
		case 0x1A02: i = 31;break;
		case 0x1A03: i = 32;break;
		case 0x1A04: i = 33;break;
		case 0x1A05: i = 34;break;
		case 0x1A06: i = 35;break;
		case 0x1A07: i = 36;break;
		case 0x1A08: i = 37;break;
		case 0x1F80: i = 38;break;
		case 0x2000: i = 39;break;
		case 0x2A00: i = 40;break;
		case 0x2A10: i = 41;break;
		case 0x2A11: i = 42;break;
		case 0x2A12: i = 43;break;
		case 0x2A13: i = 44;break;
		case 0x2A14: i = 45;break;
		case 0x2A15: i = 46;break;
		case 0x2A16: i = 47;break;
		case 0x2A17: i = 48;break;
		case 0x2A18: i = 49;break;
		case 0x2A19: i = 50;break;
		case 0x2A1A: i = 51;break;
		case 0x2A1B: i = 52;break;
		case 0x2A1C: i = 53;break;
		case 0x2A1D: i = 54;break;
		case 0x2A1E: i = 55;break;
		case 0x2A1F: i = 56;break;
		case 0x2A20: i = 57;break;
		case 0x2A21: i = 58;break;
		case 0x2A22: i = 59;break;
		case 0x2A23: i = 60;break;
		case 0x2A24: i = 61;break;
		case 0x2A25: i = 62;break;
		case 0x2A26: i = 63;break;
		case 0x2A27: i = 64;break;
		case 0x2A28: i = 65;break;
		case 0x2A29: i = 66;break;
		case 0x2A2A: i = 67;break;
		case 0x2A2B: i = 68;break;
		case 0x2A2C: i = 69;break;
		case 0x2A2D: i = 70;break;
		case 0x2A2E: i = 71;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestSlave_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestSlave_PDO_status[9] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index TestSlave_firstIndex = {
  9, /* SDO_SVR */
  0, /* SDO_CLT */
  10, /* PDO_RCV */
  15, /* PDO_RCV_MAP */
  20, /* PDO_TRS */
  29 /* PDO_TRS_MAP */
};

const quick_index TestSlave_lastIndex = {
  9, /* SDO_SVR */
  0, /* SDO_CLT */
  14, /* PDO_RCV */
  19, /* PDO_RCV_MAP */
  22, /* PDO_TRS */
  31 /* PDO_TRS_MAP */
};

const UNS16 TestSlave_ObjdictSize = sizeof(TestSlave_objdict)/sizeof(TestSlave_objdict[0]); 

CO_Data TestSlave_Data = CANOPEN_NODE_DATA_INITIALIZER(TestSlave);

