
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE_H
#define TESTSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlave_Data;
extern UNS8 OperationState_Undefined1;		/* Mapped at index 0x2000, subindex 0x01 */
extern UNS8 OperationState_Undefined2;		/* Mapped at index 0x2000, subindex 0x02 */
extern UNS8 OperationState_IO_OperationState;		/* Mapped at index 0x2000, subindex 0x03 */
extern UNS8 BMS_FirmwareVersion_Major;		/* Mapped at index 0x2A00, subindex 0x01 */
extern UNS8 BMS_FirmwareVersion_Minor;		/* Mapped at index 0x2A00, subindex 0x02 */
extern UNS8 BMS_FirmwareVersion_Build;		/* Mapped at index 0x2A00, subindex 0x03 */
extern UNS32 BMS_Information_BMS_Status;		/* Mapped at index 0x2A10, subindex 0x01 */
extern UNS32 BMS_Information_BMS_Warnings;		/* Mapped at index 0x2A10, subindex 0x02 */
extern UNS32 BMS_Information_BMS_Errors;		/* Mapped at index 0x2A10, subindex 0x03 */
extern UNS16 BMS_States_BMS_StateOfCharge;		/* Mapped at index 0x2A11, subindex 0x01 */
extern UNS16 BMS_States_BMS_StateOfHealth;		/* Mapped at index 0x2A11, subindex 0x02 */
extern UNS32 BMS_ActualVoltage;		/* Mapped at index 0x2A12, subindex 0x00*/
extern INTEGER32 BMS_ActualCurrent;		/* Mapped at index 0x2A13, subindex 0x00*/
extern INTEGER16 BMS_ActualTemp_BMS_ActualTemp1;		/* Mapped at index 0x2A14, subindex 0x01 */
extern INTEGER16 BMS_ActualTemp_BMS_ActualTemp2;		/* Mapped at index 0x2A14, subindex 0x02 */
extern INTEGER16 BMS_ActualTemp_BMS_ActualTemp3;		/* Mapped at index 0x2A14, subindex 0x03 */
extern INTEGER16 BMS_ActualTemp_BMS_ActualTemp4;		/* Mapped at index 0x2A14, subindex 0x04 */
extern UNS8 BMS_BatteryMode;		/* Mapped at index 0x2A15, subindex 0x00*/
extern UNS32 BMS_ReceivedActualVoltages_BMS1_ActualVoltage;		/* Mapped at index 0x2A16, subindex 0x01 */
extern UNS32 BMS_ReceivedActualVoltages_BMS2_ActualVoltage;		/* Mapped at index 0x2A16, subindex 0x02 */
extern UNS32 BMS_ReceivedActualVoltages_BMS3_ActualVoltage;		/* Mapped at index 0x2A16, subindex 0x03 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage1;		/* Mapped at index 0x2A17, subindex 0x01 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage2;		/* Mapped at index 0x2A17, subindex 0x02 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage3;		/* Mapped at index 0x2A17, subindex 0x03 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage4;		/* Mapped at index 0x2A17, subindex 0x04 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage5;		/* Mapped at index 0x2A17, subindex 0x05 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage6;		/* Mapped at index 0x2A17, subindex 0x06 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage7;		/* Mapped at index 0x2A17, subindex 0x07 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage8;		/* Mapped at index 0x2A17, subindex 0x08 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage9;		/* Mapped at index 0x2A17, subindex 0x09 */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage10;		/* Mapped at index 0x2A17, subindex 0x0A */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage11;		/* Mapped at index 0x2A17, subindex 0x0B */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage12;		/* Mapped at index 0x2A17, subindex 0x0C */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage13;		/* Mapped at index 0x2A17, subindex 0x0D */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage14;		/* Mapped at index 0x2A17, subindex 0x0E */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage15;		/* Mapped at index 0x2A17, subindex 0x0F */
extern UNS32 BMS_CellVoltages_BMS_CellVoltage16;		/* Mapped at index 0x2A17, subindex 0x10 */
extern UNS32 RTCBatteryTime;		/* Mapped at index 0x2A18, subindex 0x00*/
extern UNS16 BMS_TimeInformation_BMS_RemCTime;		/* Mapped at index 0x2A19, subindex 0x01 */
extern UNS16 BMS_TimeInformation_BMS_RemDTime;		/* Mapped at index 0x2A19, subindex 0x02 */
extern UNS16 BMS_CycleCount;		/* Mapped at index 0x2A1A, subindex 0x00*/
extern UNS16 BMS_ChargeCycleVoltages_BMS_VolAtStartChargeCycle;		/* Mapped at index 0x2A1B, subindex 0x01 */
extern UNS16 BMS_ChargeCycleVoltages_BMS_VolAtEndChargeCycle;		/* Mapped at index 0x2A1B, subindex 0x02 */
extern INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature1AtStartChargeCycle;		/* Mapped at index 0x2A1C, subindex 0x01 */
extern INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature1AtEndChargeCycle;		/* Mapped at index 0x2A1C, subindex 0x02 */
extern INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature2AtStartChargeCycle;		/* Mapped at index 0x2A1C, subindex 0x03 */
extern INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature2AtEndChargeCycle;		/* Mapped at index 0x2A1C, subindex 0x04 */
extern INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature3AtStartChargeCycle;		/* Mapped at index 0x2A1C, subindex 0x05 */
extern INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature3AtEndChargeCycle;		/* Mapped at index 0x2A1C, subindex 0x06 */
extern INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature4AtStartChargeCycle;		/* Mapped at index 0x2A1C, subindex 0x07 */
extern INTEGER16 BMS_ChargeCycleTemperatures_BMS_Temperature4AtEndChargeCycle;		/* Mapped at index 0x2A1C, subindex 0x08 */
extern UNS16 BMS_ChargeCycleSOC_BMS_SOCAtStartChargeCycle;		/* Mapped at index 0x2A1D, subindex 0x01 */
extern UNS16 BMS_ChargeCycleSOC_BMS_SOCAtEndChargeCycle;		/* Mapped at index 0x2A1D, subindex 0x02 */
extern UNS32 BMS_ChargeCycleTimeStamp_BMS_TimeStampAtStartChargeCycle;		/* Mapped at index 0x2A1E, subindex 0x01 */
extern UNS32 BMS_ChargeCycleTimeStamp_BMS_TimeStampAtEndChargeCycle;		/* Mapped at index 0x2A1E, subindex 0x02 */
extern INTEGER8 TemperatureWarning_BMS_HighTemperWarningLevel;		/* Mapped at index 0x2A1F, subindex 0x01 */
extern INTEGER8 TemperatureWarning_BMS_LowTemperWarningLevel;		/* Mapped at index 0x2A1F, subindex 0x02 */
extern UNS16 HighVolWarningLevel_BMS_HighVoltageWarningLevel;		/* Mapped at index 0x2A20, subindex 0x01 */
extern UNS16 HighVolWarningLevel_BMS_LowVoltageWarningLevel;		/* Mapped at index 0x2A20, subindex 0x02 */
extern UNS16 BMS_StartCapacity;		/* Mapped at index 0x2A21, subindex 0x00*/
extern INTEGER16 BMS_TemperatureExtremes_BMS_HighestTemperature1;		/* Mapped at index 0x2A22, subindex 0x01 */
extern INTEGER16 BMS_TemperatureExtremes_BMS_LowestTemperature1;		/* Mapped at index 0x2A22, subindex 0x02 */
extern INTEGER16 BMS_TemperatureExtremes_BMS_HighestTemperature2;		/* Mapped at index 0x2A22, subindex 0x03 */
extern INTEGER16 BMS_TemperatureExtremes_BMS_LowestTemperature2;		/* Mapped at index 0x2A22, subindex 0x04 */
extern INTEGER16 BMS_TemperatureExtremes_BMS_HighestTemperature3;		/* Mapped at index 0x2A22, subindex 0x05 */
extern INTEGER16 BMS_TemperatureExtremes_BMS_LowestTemperature3;		/* Mapped at index 0x2A22, subindex 0x06 */
extern INTEGER16 BMS_TemperatureExtremes_BMS_HighestTemperature4;		/* Mapped at index 0x2A22, subindex 0x07 */
extern INTEGER16 BMS_TemperatureExtremes_BMS_LowestTemperature4;		/* Mapped at index 0x2A22, subindex 0x08 */
extern UNS16 BMS_VoltageExtremes_BMS_HighestVoltage;		/* Mapped at index 0x2A23, subindex 0x01 */
extern UNS16 BMS_VoltageExtremes_BMS_LowestVoltage;		/* Mapped at index 0x2A23, subindex 0x02 */
extern UNS16 BMS_CurrentExtremes_BMS_HighestChargeCurrent;		/* Mapped at index 0x2A24, subindex 0x01 */
extern UNS16 BMS_CurrentExtremes_BMS_HighestDischargeCurrent;		/* Mapped at index 0x2A24, subindex 0x02 */
extern UNS8 BMS_DOD_BMS_MaximumDOD;		/* Mapped at index 0x2A25, subindex 0x01 */
extern UNS8 BMS_DOD_BMS_AvarageDOD;		/* Mapped at index 0x2A25, subindex 0x02 */
extern UNS16 BMS_IntervalLogPointer;		/* Mapped at index 0x2A26, subindex 0x00*/
extern UNS16 BMS_IntervalLogRequest;		/* Mapped at index 0x2A27, subindex 0x00*/
extern UNS8 BMS_IntervalLogResponse;		/* Mapped at index 0x2A28, subindex 0x00*/
extern INTEGER8 BMS_IntervalLogData[];		/* Mapped at index 0x2A29, subindex 0x00*/
extern UNS8 BMS_IntervalLogClear;		/* Mapped at index 0x2A2A, subindex 0x00*/
extern INTEGER8 BMS_CycleLogData[];		/* Mapped at index 0x2A2B, subindex 0x00*/
extern UNS8 BMS_CycleLogClear;		/* Mapped at index 0x2A2C, subindex 0x00*/
extern INTEGER8 BMS_ErrorLogData[];		/* Mapped at index 0x2A2D, subindex 0x00*/
extern UNS8 BMS_ErrorLogClear;		/* Mapped at index 0x2A2E, subindex 0x00*/

#endif // TESTSLAVE_H
